export default {
  tutorials: "টিউটোরিয়াল (Tutorial)",
  "doc-type": "DOC টাইপ (DOC Type)",
  elements: "এলিমেন্ট (Element)",
  tag: "ট্যাগ (Tag)",
  attributes: "অ্যাট্রিবিউট (Attributes)",
  paragraph: "অনুচ্ছেদ (Paragraph)",
  heading: "শিরোনাম (Heading)",
  list: "তালিকা (List)",
  font: "ফন্ট (Font)",
  link: "লিংক (Link)",
  entity: "এনটাইটি (Entity)",
  images: "ছবি (Images)",
  tables: "টেবিল (Tables)",
  colors: "রং (Colors)",
  background: "ব্যাকগ্রাউন্ড (Background)",
  frame: "ফ্রেম (Frame)",
  layout: "লেআউট (Layout)",
  comments: "মন্তব্য (Comments)",
  "embed-music": "মিউজিক (Embed Music)",
};
